language: node_js
node_js:
  - "0.10"
  - "0.12"
sudo: false
script: "npm run-script test-coverage"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"